### ISSUE TITLE
Exchanger & Soulstone = Cobbled Soulstone?

### ISSUE THREAD

**Issue by Danekjovax** [JackyyTV/Exchangers#61] opened 2019-10-26 09:36 UTC
By its nature, an exchanger swaps blocks, so how is it that using the exchanger on Soulstone results in cobbled Soulstone? Seems like an error in the block swap table. Using a regular Silk Touch pickaxe yields Soulstone as expected.

Please fix this mechanic so Soulstone can be directly harvested by exchangers.  Thanks!

![2019-10-24_22 45 08](https://user-images.githubusercontent.com/10191173/67614040-98551500-f783-11e9-9172-9b22e285ecda.png)
![2019-10-24_22 45 15](https://user-images.githubusercontent.com/10191173/67614041-9a1ed880-f783-11e9-86f9-8824f278d8db.png)

Originally posted at:
https://github.com/Freebi85/Dungeons-Dragons-Space-Shuttles/issues/435

**Comment by JackyyTV** [comment] 2019-10-26 12:51
Can you check if the "Silk Touch Mode" option is disabled in the config for DD&SS? I'd assume that's the case and hence why you're getting Cobbled Soulstone instead of Soulstone, which is an intended behaviour when that config option is disabled, you're then supposed to enanchant the Exchanger with Silk Touch to grant that capability.

**Comment by Danekjovax** [comment] 2019-10-27 03:46
Ok, I'll ask the modpack dev and see where we're at on this.  If it's the latter case, then it's understandable to add the ST enchantment. Thanks for the heads-up on that!

In my client, "Exchangers.cfg": Line 580-581:
        # If true, enables Silk Touch (gets the blocks itself rather than drops) in all Exchangers
        B:doExchangersSilkTouch=**true**

**Comment by Danekjovax** [comment] 2019-11-07 04:22
Ok, sorry for not getting back sooner.  I've checked my local config file:
"B:doExchangersSilkTouch=true"
However, it appears to be ignored.  I am in survival mode with two exchangers, one normal and one with Silk Touch.  I am targeting Soul stone, with both, and both exchangers still covert the block to cobbled version.

Am I missing something?  Please advise.

**Comment by JackyyTV** [comment] 2019-11-07 15:17
Hmm, that's really strange. I'll have to look into that further when I have time.

Currently very busy with work so I am not able to work on anything to do with MC modding yet, but hopefully over the next couple weeks when the big project at work finishes, I'll have more time to shift the focus back to MC modding. Apologies for the delay on updates.

**Comment by Danekjovax** [comment] 2019-11-09 10:08
That's fine, JackyyTV.  Further investigation from my end reveals that it may be a unique mechanic with Soulstone in particular, as many other blocks (excepting the one in #60) appear to behave normally and yield as if ST was used.  If that's the case I may need to look at pushing the issue with NetherEX and have them examine their Soulstone code.

**Comment by JackyyTV** [comment] 2020-03-15 14:34
After hours of fixing and testing, I can confirm that this issue is indeed related to #60 as my code of handing silk touch drops was causing a lot of issues. I've fixed it and will be in the next update.

See below for a demo of the fix working in action:
![](https://user-images.githubusercontent.com/11830494/76703476-dcce5680-670c-11ea-90e3-3375eb5cb36d.gif)

**Comment by Danekjovax** [comment] 2020-03-16 20:10
Many thanks, JackyyTV!  You're awesome!  ;2D

**Closed as completed** 2020-03-17 18:01 UTC
Labels: Bug

**Comment by JackyyTV** [comment] 2020-03-17 18:46
Fixed in [2.9](https://www.curseforge.com/minecraft/mc-mods/exchangers/files/2903998).
