### ISSUE TITLE
Wood oreDictionary issue

### ISSUE THREAD

**Issue by Elvarion** [JackyyTV/Exchangers#56] opened 2018-07-30 11:43 UTC
Shift+Rightclick Spruce wood to set Spruce as replacable block
Trying to replace other blocks with Spruce > "Error: Out of Block!"
Exchanger wants to replace with Oak Wook and not Spruce

- Exchangers-1.12.2-2.7.2

**Comment by JackyyTV** [comment] 2018-07-31 02:08
Duplicate of #54, has already been fixed in [2.7.3](https://minecraft.curseforge.com/projects/exchangers/files/2579652), please update to that version.

**Closed as completed by JackyyTV** 2018-07-31 02:08 UTC
Labels: Bug, Duplicate, Already Fixed
